---
title: "My title"
subtitle: "My subtitle if needed"
author: 
  - Hritik Shukla
thanks: "Code and data are available at: https://github.com/hritikshuklas/toronto-neighbourhood-crimes"
date: today
date-format: long
abstract: "First sentence. Second sentence. Third sentence. Fourth sentence."
format: pdf
number-sections: true
bibliography: references.bib
---

```{r}
#| include: false
#| warning: false
#| message: false

library(tidyverse)
```

# Introduction

You can and should cross-reference sections and sub-sections.

The remainder of this paper is structured as follows. @sec-data....

# Data {#sec-data}

The analysis for this project was done using R programming language [@citeR], and multiple libraries were used within R to help with tasks such as plotting graphs, data cleaning and manipulation. In particular, the opendatatoronto library [@opendatatoronto] was used for acquiring the dataset off of Open Data Toronto's servers, janitor [@janitor], tidyverse [@tidyverse] and dplyr [@dplyr] were used for cleaning, manipulating and testing the dataset, and ggplot2 [@ggplot2] was used for creating plots and graphs shown in the analysis.

## Data Features ##

The data contains crime data for all 158 neighborhoods of Toronto, from the year 2014 to the year 2023. The data includes counts for individual categories of crimes, such as assault, auto theft, break and entering, robbery, homicide, theft over ($5000), shooting and firearm discharges. The data also includes the crime rate for each of these categories, calculated as crimes committed per 100,000 population. These crime rates were calculated using population estimates for each neighborhood in 2023, which were provided by Environics Analytics.

## Data Collection ##

# Results

# Discussion

## First discussion point {#sec-first-point}

If my paper were 10 pages, then should be be at least 2.5 pages. The discussion is a chance to show off what you know and what you learnt from all this.

## Second discussion point

## Third discussion point

## Weaknesses and next steps

Weaknesses and next steps should also be included.

\newpage

# References
